# Generated by Django 3.2.5 on 2021-08-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='fullname')),
                ('studentID', models.CharField(blank=True, max_length=12, unique=True, verbose_name='student ID')),
                ('studentstatus', models.CharField(blank=True, choices=[('OP', 'Observation and Participation'), ('PT', 'Practice Teacher')], default='', max_length=50, verbose_name='Student Status')),
                ('professor', models.TextField(blank=True, max_length=50, verbose_name='Professor in Charge')),
                ('school', models.TextField(blank=True, max_length=50, verbose_name='School')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='fullname')),
                ('studentID', models.TextField(blank=True, max_length=12, unique=True, verbose_name='student ID')),
                ('studentstatus', models.CharField(choices=[('OP', 'Observation and Participation'), ('PT', 'Practice Teacher')], default='', max_length=50, verbose_name='Student Status')),
                ('professor', models.TextField(blank=True, max_length=50, verbose_name='Professor in Charge')),
                ('school', models.TextField(blank=True, max_length=50, verbose_name='School')),
            ],
        ),
    ]
