# Generated by Django 3.2.5 on 2021-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOPPT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='studentstatus',
            field=models.CharField(blank=True, choices=[('OP', 'Observation and Participation'), ('PT', 'Practice Teacher'), ('Done', 'Done')], default='', max_length=50, verbose_name='Student Status'),
        ),
    ]
