# Generated by Django 3.2.5 on 2021-08-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOPPT', '0002_alter_information_studentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='schedule',
            field=models.CharField(blank=True, max_length=50, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='information',
            name='professor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Professor in Charge'),
        ),
        migrations.AlterField(
            model_name='information',
            name='school',
            field=models.CharField(blank=True, max_length=50, verbose_name='School'),
        ),
    ]
